if [[ -s "/Users/hidetoshi.yajima/.zprezto/init.zsh" ]]; then
  source "/Users/hidetoshi.yajima/.zprezto/init.zsh"
  fi

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)"


export GOPATH="/Users/hidetoshi.yajima/go"
export PATH

function peco-history-selection() {
    BUFFER=`history -n 1 | tail -r  | awk '!a[$0]++' | peco`
    CURSOR=$#BUFFER
     zle reset-prompt
}

zle -N peco-history-selection
bindkey '^R' peco-history-selection

alias ...='cd ../..'
alias c='clear'
alias s='sh'
alias v='vim'
alias p='pwd'
